export type AddressSuggestion = { state: string; city: string; value: string };

export const nigeriaStateCityMap: Record<string, string[]> = {
  Abia: ["Aba", "Umuahia", "Ohafia", "Arochukwu", "Bende", "Isiala Ngwa", "Ugwunagbo", "Ukwa", "Obingwa"],
  Adamawa: ["Yola", "Mubi", "Jimeta", "Numan", "Ganye", "Hong", "Michika", "Song", "Gombi"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Oron", "Abak", "Etinan", "Ibeno", "Ikot Abasi", "Itu"],
  Anambra: ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Ihiala", "Ogidi", "Nkpor", "Otuocha", "Agulu"],
  Bauchi: ["Bauchi", "Azare", "Misau", "Jama'are", "Katagum", "Tafawa Balewa", "Ningi", "Dass", "Toro"],
  Bayelsa: ["Yenagoa", "Brass", "Kaiama", "Ogbia", "Sagbama", "Nembe", "Oporoma", "Twon-Brass", "Amassoma"],
  Benue: ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Vandeikya", "Aliade", "Ugbokolo", "Adikpo", "Wannune"],
  Borno: ["Maiduguri", "Biu", "Bama", "Gwoza", "Konduga", "Dikwa", "Monguno", "Kukawa", "Shani"],
  "Cross River": ["Calabar", "Ikom", "Ogoja", "Ugep", "Obudu", "Akamkpa", "Obubra", "Akpabuyo"],
  Delta: ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor", "Ozoro", "Koko", "Oleh", "Kwale"],
  Ebonyi: ["Abakaliki", "Afikpo", "Onueke", "Ishieke", "Ezza", "Ikwo", "Ngbo", "Uburu", "Unwana"],
  Edo: ["Benin City", "Ekpoma", "Auchi", "Uromi", "Igarra", "Irrua", "Sabongida-Ora", "Ubiaja", "Fugar"],
  Ekiti: ["Ado Ekiti", "Ikere Ekiti", "Ijero Ekiti", "Ise Ekiti", "Efon Alaaye", "Aramoko Ekiti", "Omuo Ekiti", "Ilawe Ekiti", "Emure Ekiti"],
  Enugu: ["Enugu", "Nsukka", "Agbani", "Awgu", "Udi", "Oji River", "Ezeagu", "Nkanu", "Orba"],
  "FCT Abuja": [
    "Abuja",
    "Wuse",
    "Wuse 2",
    "Maitama",
    "Asokoro",
    "Garki",
    "Jabi",
    "Utako",
    "Gwarinpa",
    "Kubwa",
    "Lugbe",
    "Apo",
    "Durumi",
    "Katampe",
    "Bwari",
    "Gwagwalada",
    "Kuje",
    "Abaji",
    "Kwali"
  ],
  Gombe: ["Gombe", "Kaltungo", "Billiri", "Dukku", "Bajoga", "Deba", "Nafada", "Akko", "Kwami"],
  Imo: ["Owerri", "Orlu", "Okigwe", "Mbaise", "Oguta", "Nkwerre", "Mgbidi", "Aboh Mbaise", "Obowo"],
  Jigawa: ["Dutse", "Hadejia", "Gumel", "Kazaure", "Ringim", "Birnin Kudu", "Kafin Hausa", "Garki", "Babura"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan", "Samaru", "Sabon Gari", "Soba", "Kagoro", "Makarfi", "Birnin Gwari"],
  Kano: ["Kano", "Wudil", "Gwarzo", "Rano", "Bichi", "Dambatta", "Kura", "Gezawa", "Ungogo"],
  Katsina: ["Katsina", "Daura", "Funtua", "Malumfashi", "Dutsin-Ma", "Kankia", "Jibia", "Mani", "Bakori"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Jega", "Bagudo", "Aliero", "Koko", "Bunza"],
  Kogi: ["Lokoja", "Okene", "Kabba", "Anyigba", "Idah", "Ajaokuta", "Ankpa", "Ogaminana", "Ejule"],
  Kwara: ["Ilorin", "Offa", "Jebba", "Omu-Aran", "Lafiagi", "Pategi", "Kaiama", "Share", "Ilesha Baruba"],
  Lagos: [
    "Lagos Island",
    "Ikoyi",
    "Victoria Island",
    "Ikeja",
    "Maryland",
    "Ojodu",
    "Ogudu",
    "Magodo",
    "Opebi",
    "Allen",
    "Yaba",
    "Akoka",
    "Surulere",
    "Lekki",
    "Lekki Phase 1",
    "Ajah",
    "Sangotedo",
    "Ikate",
    "Chevron",
    "Ikorodu",
    "Gbagada",
    "Isolo",
    "Ilupeju",
    "Mushin",
    "Agege",
    "Festac",
    "Amuwo Odofin",
    "Ojo",
    "Badagry",
    "Epe",
    "Apapa"
  ],
  Nasarawa: ["Lafia", "Keffi", "Akwanga", "Karu", "Nasarawa", "Doma", "Kokona", "Nasarawa Eggon", "Wamba"],
  Niger: ["Minna", "Bida", "Suleja", "Kontagora", "Lapai", "New Bussa", "Mokwa", "Agaie", "Shiroro"],
  Ogun: ["Abeokuta", "Ota", "Sango Ota", "Magboro", "Arepo", "Ibafo", "Mowe", "Sagamu", "Ifo", "Ijebu Ode", "Ilaro", "Ayetoro", "Ago Iwoye"],
  Ondo: ["Akure", "Ondo", "Owo", "Ikare", "Okitipupa", "Ore", "Igbokoda", "Idanre", "Irele"],
  Osun: ["Osogbo", "Ile-Ife", "Ilesa", "Ede", "Ikirun", "Ejigbo", "Iwo", "Ila Orangun", "Modakeke"],
  Oyo: ["Ibadan", "Bodija", "Mokola", "Dugbe", "Challenge", "Bashorun", "Moniya", "Ogbomoso", "Oyo", "Iseyin", "Saki", "Eruwa", "Igboho", "Kisi"],
  Plateau: ["Jos", "Bukuru", "Pankshin", "Shendam", "Vom", "Langtang", "Mangu", "Bassa", "Riyom"],
  Rivers: ["Port Harcourt", "Old GRA", "Trans Amadi", "Rumuokoro", "Rumuola", "Obio-Akpor", "Bonny", "Omoku", "Eleme", "Ahoada", "Degema", "Bori", "Isiokpo"],
  Sokoto: ["Sokoto", "Tambuwal", "Wurno", "Gwadabawa", "Illela", "Goronyo", "Rabah", "Bodinga", "Kware"],
  Taraba: ["Jalingo", "Wukari", "Bali", "Takum", "Serti", "Gembu", "Mutum Biyu", "Zing", "Ibi"],
  Yobe: ["Damaturu", "Potiskum", "Nguru", "Gashua", "Geidam", "Buni Yadi", "Fika", "Machina", "Bade"],
  Zamfara: ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka", "Tsafe", "Shinkafi", "Maradun", "Gummi", "Bakura"]
};

export const nigerianStates = Object.keys(nigeriaStateCityMap).sort();

export const fallbackNigeriaAddressSuggestions: AddressSuggestion[] = [
  { state: "Lagos", city: "Ikeja", value: "No 64 Adeniyi Jones, Ladipo Oluwole Busstop, Ikeja, Lagos" },
  { state: "Lagos", city: "Ikeja", value: "12 Opebi Road, Salvation Busstop, Ikeja, Lagos" },
  { state: "Lagos", city: "Ikeja", value: "18 Obafemi Awolowo Way, Allen Roundabout, Ikeja, Lagos" },
  { state: "Lagos", city: "Ikeja", value: "7 Toyin Street, Ikeja Along, Ikeja, Lagos" },
  { state: "Lagos", city: "Ikeja", value: "25 Isaac John Street, GRA, Ikeja, Lagos" },
  { state: "Lagos", city: "Lagos", value: "14 Broad Street, CMS Busstop, Lagos Island, Lagos" },
  { state: "Lagos", city: "Lagos", value: "8 Marina Road, Opposite Leventis, Lagos Island, Lagos" },
  { state: "Lagos", city: "Lagos", value: "22 Idumagbo Avenue, Balogun Market Area, Lagos Island, Lagos" },
  { state: "Lagos", city: "Ikoyi", value: "9 Bourdillon Road, Falomo Bridge Area, Ikoyi, Lagos" },
  { state: "Lagos", city: "Ikoyi", value: "14 Awolowo Road, Keffi Busstop, Ikoyi, Lagos" },
  { state: "Lagos", city: "Victoria Island", value: "7 Akin Adesola Street, Eko Hotel Roundabout, Victoria Island, Lagos" },
  { state: "Lagos", city: "Victoria Island", value: "22 Adetokunbo Ademola Street, Bonny Camp Busstop, Victoria Island, Lagos" },
  { state: "Lagos", city: "Yaba", value: "5 Herbert Macaulay Way, Sabo Busstop, Yaba, Lagos" },
  { state: "Lagos", city: "Yaba", value: "11 Commercial Avenue, Alagomeji, Yaba, Lagos" },
  { state: "Lagos", city: "Yaba", value: "3 University Road, Unilag Second Gate, Akoka, Yaba, Lagos" },
  { state: "Lagos", city: "Lekki", value: "21 Admiralty Way, Lekki Phase 1, Lekki, Lagos" },
  { state: "Lagos", city: "Lekki", value: "32 Fola Osibo Road, Jakande Roundabout, Lekki, Lagos" },
  { state: "Lagos", city: "Lekki", value: "9 Freedom Way, Ikate Elegushi, Lekki, Lagos" },
  { state: "Lagos", city: "Surulere", value: "16 Bode Thomas Street, Adeniran Ogunsanya Busstop, Surulere, Lagos" },
  { state: "Lagos", city: "Surulere", value: "41 Adeniran Ogunsanya Street, Shoprite Area, Surulere, Lagos" },
  { state: "Lagos", city: "Agege", value: "27 Old Abeokuta Road, Pen Cinema, Agege, Lagos" },
  { state: "Lagos", city: "Ikorodu", value: "14 Lagos Road, Ita Elewa Busstop, Ikorodu, Lagos" },
  { state: "Lagos", city: "Festac", value: "House 12 Road 21, 2nd Avenue, Festac Town, Lagos" },

  { state: "FCT Abuja", city: "Abuja", value: "12 Aminu Kano Crescent, Wuse 2, Abuja, FCT Abuja" },
  { state: "FCT Abuja", city: "Abuja", value: "18 Aguiyi Ironsi Street, Maitama, Abuja, FCT Abuja" },
  { state: "FCT Abuja", city: "Abuja", value: "7 Adetokunbo Ademola Crescent, Wuse 2, Abuja, FCT Abuja" },
  { state: "FCT Abuja", city: "Abuja", value: "24 Ahmadu Bello Way, Area 11, Garki, Abuja, FCT Abuja" },
  { state: "FCT Abuja", city: "Abuja", value: "9 First Avenue, Gwarinpa 1st Gate, Gwarinpa, Abuja, FCT Abuja" },
  { state: "FCT Abuja", city: "Wuse", value: "Plot 245 Herbert Macaulay Way, Wuse Market Area, Wuse, FCT Abuja" },
  { state: "FCT Abuja", city: "Maitama", value: "6 Mississippi Street, Transcorp Hilton Area, Maitama, FCT Abuja" },
  { state: "FCT Abuja", city: "Gwagwalada", value: "15 Market Road, Opposite University of Abuja Teaching Hospital, Gwagwalada, FCT Abuja" },

  { state: "Rivers", city: "Port Harcourt", value: "3 Aba Road, Waterlines Junction, Port Harcourt, Rivers" },
  { state: "Rivers", city: "Port Harcourt", value: "14 Olu Obasanjo Road, GRA Phase 2, Port Harcourt, Rivers" },
  { state: "Rivers", city: "Port Harcourt", value: "8 Forces Avenue, Old GRA, Port Harcourt, Rivers" },
  { state: "Rivers", city: "Port Harcourt", value: "22 East-West Road, Rumuokoro Roundabout, Port Harcourt, Rivers" },
  { state: "Rivers", city: "Port Harcourt", value: "11 Peter Odili Road, Trans Amadi Junction, Port Harcourt, Rivers" },
  { state: "Rivers", city: "Obio-Akpor", value: "17 Ikwerre Road, Mile 3 Market, Obio-Akpor, Rivers" },

  { state: "Ogun", city: "Abeokuta", value: "5 Quarry Road, Kuto Roundabout, Abeokuta, Ogun" },
  { state: "Ogun", city: "Abeokuta", value: "18 Presidential Boulevard, Oke Mosan, Abeokuta, Ogun" },
  { state: "Ogun", city: "Abeokuta", value: "9 Panseke Road, Panseke Busstop, Abeokuta, Ogun" },
  { state: "Ogun", city: "Ota", value: "24 Idiroko Road, Toll Gate Busstop, Ota, Ogun" },
  { state: "Ogun", city: "Ota", value: "7 Joju Road, Joju Busstop, Ota, Ogun" },
  { state: "Ogun", city: "Mowe", value: "12 Redemption Camp Road, Lotto Busstop, Mowe, Ogun" },
  { state: "Ogun", city: "Mowe", value: "6 Mowe Ofada Road, Mowe Town, Mowe, Ogun" },
  { state: "Ogun", city: "Sagamu", value: "10 Akarigbo Road, Sagamu Interchange, Sagamu, Ogun" },
  { state: "Ogun", city: "Ifo", value: "4 Ifo Market Road, Ifo Roundabout, Ifo, Ogun" },

  { state: "Oyo", city: "Ibadan", value: "15 Ring Road, Cocoa House Area, Ibadan, Oyo" },
  { state: "Oyo", city: "Ibadan", value: "8 Queen Elizabeth Road, Mokola Roundabout, Ibadan, Oyo" },
  { state: "Oyo", city: "Ibadan", value: "27 Bodija Road, Bodija Market Area, Ibadan, Oyo" },
  { state: "Oyo", city: "Ibadan", value: "19 University of Ibadan Road, UI First Gate, Ibadan, Oyo" },
  { state: "Oyo", city: "Ibadan", value: "31 Awolowo Avenue, Old Bodija, Ibadan, Oyo" },
  { state: "Oyo", city: "Ibadan", value: "6 Dugbe Road, Dugbe Market Area, Ibadan, Oyo" },
  { state: "Oyo", city: "Ibadan", value: "11 Akala Expressway, Challenge Busstop, Ibadan, Oyo" },

  { state: "Enugu", city: "Enugu", value: "13 Ogui Road, Holy Ghost Busstop, Enugu, Enugu" },
  { state: "Enugu", city: "Nsukka", value: "7 University Road, UNN Main Gate, Nsukka, Enugu" },
  { state: "Kwara", city: "Ilorin", value: "18 Taiwo Road, Challenge Junction, Ilorin, Kwara" },
  { state: "Kwara", city: "Ilorin", value: "9 Fate Road, Tanke Junction, Ilorin, Kwara" },
  { state: "Edo", city: "Benin City", value: "12 Sapele Road, Ring Road, Benin City, Edo" },
  { state: "Akwa Ibom", city: "Uyo", value: "22 Wellington Bassey Way, Plaza Junction, Uyo, Akwa Ibom" }
];
