export type AddressSuggestion = { state: string; city: string; value: string };

export const nigeriaStateCityMap: Record<string, string[]> = {
  Abia: ["Aba", "Umuahia", "Ohafia", "Arochukwu", "Bende", "Isiala Ngwa", "Ugwunagbo", "Ukwa", "Obingwa"],
  Adamawa: ["Yola", "Mubi", "Jimeta", "Numan", "Ganye", "Hong", "Michika", "Song", "Gombi"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Oron", "Abak", "Etinan", "Ibeno", "Ikot Abasi", "Itu"],
  Anambra: ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Ihiala", "Ogidi", "Nkpor", "Otuocha", "Agulu"],
  Bauchi: ["Bauchi", "Azare", "Misau", "Jama'are", "Katagum", "Tafawa Balewa", "Ningi", "Dass", "Toro"],
  Bayelsa: ["Yenagoa", "Brass", "Kaiama", "Ogbia", "Sagbama", "Nembe", "Oporoma", "Twon-Brass", "Amassoma"],
  Benue: ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Vandeikya", "Aliade", "Ugbokolo", "Adikpo", "Wannune"],
  Borno: ["Maiduguri", "Biu", "Bama", "Gwoza", "Konduga", "Dikwa", "Monguno", "Kukawa", "Shani"],
  "Cross River": ["Calabar", "Ikom", "Ogoja", "Ugep", "Obudu", "Akamkpa", "Obubra", "Akpabuyo"],
  Delta: ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor", "Ozoro", "Koko", "Oleh", "Kwale"],
  Ebonyi: ["Abakaliki", "Afikpo", "Onueke", "Ishieke", "Ezza", "Ikwo", "Ngbo", "Uburu", "Unwana"],
  Edo: ["Benin City", "Ekpoma", "Auchi", "Uromi", "Igarra", "Irrua", "Sabongida-Ora", "Ubiaja", "Fugar"],
  Ekiti: ["Ado Ekiti", "Ikere Ekiti", "Ijero Ekiti", "Ise Ekiti", "Efon Alaaye", "Aramoko Ekiti", "Omuo Ekiti", "Ilawe Ekiti", "Emure Ekiti"],
  Enugu: ["Enugu", "Nsukka", "Agbani", "Awgu", "Udi", "Oji River", "Ezeagu", "Nkanu", "Orba"],
  "FCT Abuja": ["Abuja", "Gwagwalada", "Kuje", "Bwari", "Abaji", "Kwali", "Gwarinpa", "Wuse", "Maitama"],
  Gombe: ["Gombe", "Kaltungo", "Billiri", "Dukku", "Bajoga", "Deba", "Nafada", "Akko", "Kwami"],
  Imo: ["Owerri", "Orlu", "Okigwe", "Mbaise", "Oguta", "Nkwerre", "Mgbidi", "Aboh Mbaise", "Obowo"],
  Jigawa: ["Dutse", "Hadejia", "Gumel", "Kazaure", "Ringim", "Birnin Kudu", "Kafin Hausa", "Garki", "Babura"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan", "Samaru", "Sabon Gari", "Soba", "Kagoro", "Makarfi", "Birnin Gwari"],
  Kano: ["Kano", "Wudil", "Gwarzo", "Rano", "Bichi", "Dambatta", "Kura", "Gezawa", "Ungogo"],
  Katsina: ["Katsina", "Daura", "Funtua", "Malumfashi", "Dutsin-Ma", "Kankia", "Jibia", "Mani", "Bakori"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Jega", "Bagudo", "Aliero", "Koko", "Bunza"],
  Kogi: ["Lokoja", "Okene", "Kabba", "Anyigba", "Idah", "Ajaokuta", "Ankpa", "Ogaminana", "Ejule"],
  Kwara: ["Ilorin", "Offa", "Jebba", "Omu-Aran", "Lafiagi", "Pategi", "Kaiama", "Share", "Ilesha Baruba"],
  Lagos: ["Lagos", "Ikeja", "Lekki", "Ikorodu", "Epe", "Badagry", "Surulere", "Yaba", "Agege", "Festac"],
  Nasarawa: ["Lafia", "Keffi", "Akwanga", "Karu", "Nasarawa", "Doma", "Kokona", "Nasarawa Eggon", "Wamba"],
  Niger: ["Minna", "Bida", "Suleja", "Kontagora", "Lapai", "New Bussa", "Mokwa", "Agaie", "Shiroro"],
  Ogun: ["Abeokuta", "Ota", "Ijebu Ode", "Sagamu", "Ilaro", "Ayetoro", "Ifo", "Mowe", "Ago Iwoye"],
  Ondo: ["Akure", "Ondo", "Owo", "Ikare", "Okitipupa", "Ore", "Igbokoda", "Idanre", "Irele"],
  Osun: ["Osogbo", "Ile-Ife", "Ilesa", "Ede", "Ikirun", "Ejigbo", "Iwo", "Ila Orangun", "Modakeke"],
  Oyo: ["Ibadan", "Ogbomoso", "Oyo", "Iseyin", "Saki", "Eruwa", "Igboho", "Kisi", "Moniya"],
  Plateau: ["Jos", "Bukuru", "Pankshin", "Shendam", "Vom", "Langtang", "Mangu", "Bassa", "Riyom"],
  Rivers: ["Port Harcourt", "Obio-Akpor", "Bonny", "Omoku", "Eleme", "Ahoada", "Degema", "Bori", "Isiokpo"],
  Sokoto: ["Sokoto", "Tambuwal", "Wurno", "Gwadabawa", "Illela", "Goronyo", "Rabah", "Bodinga", "Kware"],
  Taraba: ["Jalingo", "Wukari", "Bali", "Takum", "Serti", "Gembu", "Mutum Biyu", "Zing", "Ibi"],
  Yobe: ["Damaturu", "Potiskum", "Nguru", "Gashua", "Geidam", "Buni Yadi", "Fika", "Machina", "Bade"],
  Zamfara: ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka", "Tsafe", "Shinkafi", "Maradun", "Gummi", "Bakura"]
};

export const nigerianStates = Object.keys(nigeriaStateCityMap).sort();

export const fallbackNigeriaAddressSuggestions: AddressSuggestion[] = [
  { state: "Lagos", city: "Lagos", value: "1st Floor, Senate Building, University of Lagos, Akoka-Yaba, Lagos" },
  { state: "Lagos", city: "Ikeja", value: "Block 22 & 23, The Secretariat, Obafemi Awolowo Way, Alausa, Ikeja, Lagos" },
  { state: "Lagos", city: "Ikeja", value: "Block 16, The Secretariat Annex, Alausa, Ikeja, Lagos, Nigeria" },
  { state: "Lagos", city: "Ikeja", value: "3 Obafemi Awolowo Way, Alausa, Ikeja, Lagos" },
  { state: "Lagos", city: "Ikeja", value: "2 Oba Akran Avenue, Ikeja, Lagos" },
  { state: "Lagos", city: "Ikeja", value: "117 Obafemi Awolowo Way, Allen Junction, Ikeja, Lagos" },
  { state: "Lagos", city: "Yaba", value: "University of Lagos, Akoka Rd, Yaba, Lagos" },
  { state: "Lagos", city: "Yaba", value: "Kosoko Drive, University of Lagos, Akoka-Yaba, Lagos" },
  { state: "Lagos", city: "Ojo", value: "Main Campus, KM 15, Badagry Expressway, Ojo, Lagos" },
  { state: "FCT Abuja", city: "Abuja", value: "Main Campus, Airport Road, Abuja, FCT, Nigeria" },
  { state: "FCT Abuja", city: "Abuja", value: "University of Abuja Main Campus, Airport Road, Abuja, FCT, Nigeria" },
  { state: "Rivers", city: "Port Harcourt", value: "University of Port Harcourt, East-West Road, PMB 5323, Choba, Rivers State, Nigeria" },
  { state: "Rivers", city: "Port Harcourt", value: "Plot F/24 B1, Chinua Worlu Drive, Off Abacha Road, GRA Phase III, Port Harcourt, Rivers State, Nigeria" },
  { state: "Edo", city: "Benin City", value: "P.M.B. 1154, Ugbowo, Benin City, Edo State, Nigeria" },
  { state: "Edo", city: "Benin City", value: "Institute of Education, University of Benin, Ekenwan Campus, Benin City, Edo State, Nigeria" },
  { state: "Akwa Ibom", city: "Uyo", value: "Nwaniba Road, Uyo, Akwa Ibom State, Nigeria" },
  { state: "Akwa Ibom", city: "Uyo", value: "Ikpa Road, Uyo, Akwa Ibom State, Nigeria" },
  { state: "Oyo", city: "Ibadan", value: "University Advancement Centre, 1 Obong Road, University of Ibadan, Ibadan, Nigeria" },
  { state: "Oyo", city: "Ibadan", value: "Bursary Department, Central Admin, University of Ibadan, Ibadan, Oyo State, Nigeria" },
  { state: "Enugu", city: "Nsukka", value: "University of Nigeria, Nsukka, Enugu State, Nigeria" },
  { state: "Enugu", city: "Nsukka", value: "Opposite Eyo-Eta Hostel, University of Nigeria, Nsukka, Enugu State, Nigeria" },
  { state: "Enugu", city: "Enugu", value: "Department of Architecture, Faculty of Environmental Sciences, University of Nigeria, Enugu Campus, Enugu State, Nigeria" },
  { state: "Kwara", city: "Ilorin", value: "P.M.B. 1515, Ilorin, Nigeria" },
  { state: "Kwara", city: "Ilorin", value: "Ground Floor, Centre for Management and Leadership Ilorin, University of Ilorin, Ilorin, Nigeria" }
];
